# Generated by Django 4.2.8 on 2024-02-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordApp', '0002_safebox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordmanagerdatamodel',
            name='userName',
        ),
    ]
