# Generated by Django 4.2.8 on 2024-02-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passwordApp', '0003_remove_passwordmanagerdatamodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanagerdatamodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
