# Generated by Django 4.2.8 on 2024-02-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwordApp', '0004_passwordmanagerdatamodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanagerdatamodel',
            name='safebox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_data', to='passwordApp.safebox'),
        ),
        migrations.AlterField(
            model_name='safebox',
            name='password_manager_data',
            field=models.ManyToManyField(related_name='safe_boxes', to='passwordApp.passwordmanagerdatamodel'),
        ),
    ]
