# Generated by Django 4.2.8 on 2024-02-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwordApp', '0005_passwordmanagerdatamodel_safebox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordmanagerdatamodel',
            name='safebox',
        ),
        migrations.RemoveField(
            model_name='safebox',
            name='password_manager_data',
        ),
        migrations.AddField(
            model_name='safebox',
            name='password_manager_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safe_box', to='passwordApp.passwordmanagerdatamodel'),
        ),
    ]
