# Generated by Django 4.2.8 on 2024-02-16 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwordApp', '0006_remove_passwordmanagerdatamodel_safebox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanagerdatamodel',
            name='safebox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_data', to='passwordApp.safebox'),
        ),
    ]
