# Generated by Django 4.2.8 on 2024-02-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwordApp', '0007_passwordmanagerdatamodel_safebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanagerdatamodel',
            name='safebox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_data', to='passwordApp.safebox'),
        ),
    ]
